version: '3'
services:
  analyzer-node:
      build: .
      image: analyzer-node
      # command: echo analizer-node > /usr/share/nginx/html/index.html
      volumes:
        - ./src:/app/src
        - ../database:/app/database
      container_name: analyzer-node
      command: /bin/sh
      tty: true 
      stdin_open: true
      init: true
      working_dir: /app/