version: "3"
services:

  # データ解析ノード
  analyzer-node:
      build: ./analyzer-node
      image: analyzer-node
      volumes:
        - ./analyzer-node/build:/app/src
        - ./database:/app/database
      container_name: analyzer-node
      command: node /app/src/server.js
      tty: true 
      init: true
      working_dir: /app/
      ports:
        - 2000:2000
      networks:
        inside:
          ipv4_address: 192.168.10.3
        surface: 

  user_db:
    build: ./user_db
    image: user_db
    container_name: user_db
    ports:
      - 3306:3306 
    volumes:
      - ./user_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      inside:
        ipv4_address: 192.168.10.5

  # マップアプリ(ビジュアライザ)
  visualizer-app:
    build: ./visualizer-app
    image: visualizer-app
    container_name: visualizer-app
    volumes:
      - ./database:/app/database
      - ./visualizer-app:/app
      - /app/node_modules
      - /app/.next
    init: true
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      inside:
        ipv4_address: 192.168.10.4
      surface:
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - MAIL_AUTH_USER=aytysd@gmail.com
      - MAIL_AUTH_PASS=2suH_VMNZPiBgpK_46BW



networks:
  surface:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  inside:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  db-bus:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.255.0/24


