version: "3"
services:
  # リバースプロキシ
  # reverse-proxy:
  #   build: ./reverse-proxy
  #   image: reverse-proxy-img:latest
  #   container_name: reverse-proxy
  #   depends_on:
  #     - notification-app
  #     - visualizer-app
  #     - analyzer-node
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./reverse-proxy/config/nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - surface
  #     - inside
  #   environment:
  #     - TZ=Asia/Tokyo

  # データ解析ノード
  analyzer-node:
      build: ./analyzer-node
      image: analyzer-node
      volumes:
        - ./analyzer-node/mount_ws:/app/src
      container_name: analyzer-node
      command: node /app/src/dist/server.js
      tty: true 
      init: true
      working_dir: /app/
      networks:
        inside:
          ipv4_address: 192.168.10.3



  # 通知アプリ
  # notification-app:
  #   # build: ./notification-app
  #   # image: notification-app-img
  #   image: nginx # demo image
  #   container_name: notification-app
  #   # ports:
  #   #   - 
  #   # volumes:
  #   #   - 
  #   # command: echo notification-app > /usr/share/nginx/html/index.html
  #   # echoコマンドが終了するとコンテナもなぜか終了するからコメントアウトした
  #   networks:
  #     - inside

  # マップアプリ(ビジュアライザ)
  visualizer-app:
    build: ./visualizer-app
    image: visualizer-app
    container_name: visualizer-app
    volumes:
      - ./visualizer-app/src:/app/src
      - ./visualizer-app/src/config/httpd.conf:/etc/apache2/httpd.conf
    init: true
    command: ["/usr/sbin/httpd", "-D", "FOREGROUND"]
    tty: true
    stdin_open: true
    ports:
      - 8080:80
    networks:
      inside:
        ipv4_address: 192.168.10.5
      surface:



networks:
  surface:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/30
  inside:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/28
  db-bus:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.255.0/29


