version: '3'
services:
  visualizer-app:
    build: .
    image: visualizer-app
    # image: nginx  # デモ用
    container_name: visualizer-app
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./src/config/httpd.conf:/etc/apache2/httpd.conf
      - ../database:/app/database
    init: true
    command: node src/app.js
    tty: true 
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true