version: '3'
services:
  visualizer-app:
    build: .
    image: visualizer-app
    container_name: visualizer-app
    ports:
      - 3000:3000
    volumes:
      # - ./src:/app/src
      # - ./public:/app/public
      # - ./node_modules:/app/node_modules
      # - ../database:/app/database
      # - ./tsconfig.json:/app/
      - ../database:/app/database
      - ./:/app
      - /app/node_modules
      - /app/.next
    init: true
    tty: true 
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
