"use client";

import React from 'react';

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import './body.css';
import Footer from './footer';

import { DateTimeListProvider } from '@/providers/DateTimeListProvider';
import { SelectedTimingProvider } from '@/providers/SelectedTimingProvider';
import { DisplayDataProvider } from '@/providers/SelectedDataProvider';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DateTimeListProvider>
          <DisplayDataProvider>
            <SelectedTimingProvider>
              {children}
            </SelectedTimingProvider>
          </DisplayDataProvider>
        </DateTimeListProvider>
        <Footer/>
      </body>
    </html>
  );
}




